### ISSUE TITLE
Project does not have any code style

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#968]
1. Find good formatting tool (probably clang-format)
1. Run it on CI and fail the whole build if the PR is not formatted properly

**Comment by rafaelffilho** [comment]
Some usefull links for clang-format

- [Ofiicial documentation](https://clang.llvm.org/docs/ClangFormat.html)
- [My cofinguration file, for an example](https://github.com/rafaelffilho/RafaOS/blob/master/.clang-format)

As I don't know what is the version of clang-format on NixOS that link goes to the latest version, you need to check this because the configuration file may not be compatible.

**Comment by bepzi** [comment]
I concatenated all of Nothing's source code and told Emacs to guess at what it thought the code style was.

```elisp
(c-add-style "tsoding"
             '("k&r"
               (indent-tabs-mode . nil)
               
               (c-basic-offset . 4)     ; Guessed value
               (c-offsets-alist
                (arglist-cont . 0)      ; Guessed value
                (arglist-intro . +)     ; Guessed value
                (block-close . 0)       ; Guessed value
                (brace-list-close . 0)  ; Guessed value
                (brace-list-entry . 0)  ; Guessed value
                (brace-list-intro . +)  ; Guessed value
                (case-label . 0)        ; Guessed value
                (class-close . 0)       ; Guessed value
                (class-open . 0)        ; Guessed value
                (defun-block-intro . +) ; Guessed value
                (defun-close . 0)       ; Guessed value
                (defun-open . 0)        ; Guessed value
                (inclass . +)           ; Guessed value
                (statement . 0)         ; Guessed value
                (statement-block-intro . +) ; Guessed value
                (statement-case-intro . +) ; Guessed value
                (statement-cont . +)    ; Guessed value
                (topmost-intro . 0)     ; Guessed value
                (topmost-intro-cont . 0))))  ; Guessed value

(setq-default c-default-style '((java-mode . "java")
                                (awk-mode . "awk")
                                (other . "tsoding")))
```

@rexim You may want to consider adding this to your `.emacs.d` if the style you use for Nothing is consistent with how you normally program C/C++.

**Comment by bepzi** [comment]
First attempt:

```yaml
# -*- mode: yaml;-*-
---
Language: Cpp  # C/C++

BasedOnStyle: Webkit

IndentWidth: 4
TabWidth: 4
UseTab: Never
ColumnLimit: 80

AlignAfterOpenBracket: DontAlign
# AlignAfterOpenBracket: Align
# AlignAfterOpenBracket: AlwaysBreak

AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: false
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false

# When function declarationss/invocations are too long to fit on one
# line, all parameters/arguments will be aligned onto separate lines
BinPackParameters: false
BinPackArguments: false

BreakBeforeBinaryOperators: NonAssignment

MaxEmptyLinesToKeep: 1  # Allow no more than 1 consecutive empty line

PointerAlignment: Right  # void *my_ptr;

SortIncludes: true
IncludeBlocks: Preserve

ReflowComments: true

SpaceAfterCStyleCast: false
IndentCaseLabels: false

AlwaysBreakAfterReturnType: None  # int my_func()
```

@rexim You'll have to decide what you prefer regarding `AlignAfterOpenBracket`.
